"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { changeCredits, creditMemberHistory, type CreditCommand } from "./actions";

export interface CreditMember { id: string; email: string; status: string; team_name: string | null; pricing_policy: string; available: number; reserved: number; used: number; next_expires: string | null; plan_id: string | null; subscription_status: string | null; review_units: number; }
export interface CreditPlan { id: string; name: string; monthly_units: number; price_krw: number; active: boolean; }
type History = { grants: { id: string; kind: string; granted_units: number; consumed_units: number; reserved_units: number; expires_at: string; revoked_at: string | null; reason: string }[]; pending: { request_id: string; operation: string; requested_units: number; credit_phase: string; credit_quote: { outputs: number[] } }[]; audit: { id: string; action: string; reason: string; created_at: string }[] };
const field = "rounded border bg-background p-2 text-sm";
const button = "rounded border px-3 py-2 text-sm disabled:opacity-40";
const date = (value: string | null) => value ? new Date(value).toLocaleDateString("ko-KR", { timeZone: "Asia/Seoul" }) : "—";
const number = (form: FormData, key: string) => Number(form.get(key));
const text = (form: FormData, key: string) => String(form.get(key) ?? "");

export function MembersClient({ members, plans, enabled }: { members: CreditMember[]; plans: CreditPlan[]; enabled: boolean }) {
  const router = useRouter();
  const [selected, setSelected] = useState<string[]>([]);
  const [focus, setFocus] = useState<CreditMember | null>(null);
  const [history, setHistory] = useState<History | null>(null);
  const [notice, setNotice] = useState("");
  const [pending, start] = useTransition();
  const [retry, setRetry] = useState<CreditCommand | null>(null);
  const [review, setReview] = useState<CreditCommand | null>(null);
  function submit(command: CreditCommand) { setReview(command); setNotice(""); }
  function execute(command: CreditCommand) {
    start(async () => {
      const result = await changeCredits(command); setNotice(result.message); setReview(null);
      setRetry(result.ok ? null : command);
      if (result.ok) { router.refresh(); if (focus) try { setHistory(await creditMemberHistory(focus.id)); } catch { setHistory(null); } }
    });
  }
  function open(member: CreditMember) {
    setFocus(member); setHistory(null); setNotice("");
    start(async () => { try { setHistory(await creditMemberHistory(member.id)); } catch (error) { setNotice(error instanceof Error ? error.message : "이력을 읽지 못했습니다."); } });
  }
  function exportCsv() {
    const cell = (value: unknown) => `"${String(value ?? "").replace(/^[=+\-@\t\r]/, "'$&").replaceAll('"', '""')}"`;
    const rows = [["이메일","상태","기준","사용 가능","처리 중","확인 대기","사용","만료","구독"], ...members.map(m => [m.email,m.status,m.pricing_policy,m.available,m.reserved,m.review_units,m.used,m.next_expires,m.plan_id])];
    const url = URL.createObjectURL(new Blob(["\uFEFF" + rows.map(row => row.map(cell).join(",")).join("\r\n")], { type: "text/csv;charset=utf-8" }));
    const a = document.createElement("a"); a.href = url; a.download = "members-current-page.csv"; a.click(); URL.revokeObjectURL(url);
  }
  return <div className="space-y-4">
    <div className="flex justify-between gap-3"><p className="text-sm">현재 페이지 {selected.length}명 선택</p><button className={button} onClick={exportCsv}>현재 페이지 CSV</button></div>
    <div className="overflow-x-auto rounded-xl border"><table className="w-full whitespace-nowrap text-left text-sm"><thead className="bg-muted"><tr><th className="p-3"><input type="checkbox" aria-label="현재 페이지 모두 선택" checked={members.length > 0 && selected.length === members.length} onChange={e => setSelected(e.target.checked ? members.map(m => m.id) : [])} /></th>{["회원","기준 / 구독","사용 가능","처리 중","이번 달 사용","만료",""].map((label, i) => <th className="p-3" key={i}>{label}</th>)}</tr></thead><tbody>{members.map(m => <tr key={m.id} className="border-t"><td className="p-3"><input aria-label={`${m.email} 선택`} type="checkbox" checked={selected.includes(m.id)} onChange={e => setSelected(e.target.checked ? [...selected, m.id] : selected.filter(id => id !== m.id))} /></td><td className="p-3">{m.email}<small className="block text-muted-foreground">{m.status} · {m.team_name ?? "개인"}</small></td><td className="p-3">{m.pricing_policy === "image-v2" ? "이미지 크레딧" : "기존 원가 기준"}<small className="block">{m.plan_id ?? "구독 없음"}</small></td><td className="p-3 font-semibold">{m.available}</td><td className="p-3">{m.reserved}{m.review_units > 0 && <small className="block text-amber-600">확인 대기 {m.review_units}</small>}</td><td className="p-3">{m.used}</td><td className="p-3">{date(m.next_expires)}</td><td className="p-3"><button className={button} disabled={!enabled || pending} onClick={() => open(m)}>관리·이력</button></td></tr>)}</tbody></table>{!members.length && <p className="p-8 text-center text-sm text-muted-foreground">조회된 회원이 없습니다.</p>}</div>
    <details className="rounded-xl border p-4"><summary className="cursor-pointer font-medium">선택 회원에게 지급</summary><form className="mt-4 flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); submit({ kind: "grant", users: selected, grantKind: text(f,"grantKind") as "purchase" | "bonus", units: number(f,"units"), amount: number(f,"amount"), expires: text(f,"expires") ? new Date(`${text(f,"expires")}T00:00:00+09:00`).toISOString() : null, reason: text(f,"reason"), action: crypto.randomUUID() }); }}>
      <label className="grid gap-1 text-sm">종류<select className={field} name="grantKind"><option value="purchase">구매 · 3개월</option><option value="bonus">추가 지급 · 만료일 지정</option></select></label><label className="grid gap-1 text-sm">1명당 크레딧<input className={field} name="units" type="number" min="1" max="1000000" required /></label><label className="grid gap-1 text-sm">1명당 수령액(원)<input className={field} name="amount" type="number" min="0" defaultValue="0" required /></label><label className="grid gap-1 text-sm">추가 지급 만료일(KST)<input className={field} name="expires" type="date" /></label><label className="grid gap-1 text-sm">지급 사유<input className={field} name="reason" minLength={3} required /></label><button className={button} disabled={!enabled || pending || !selected.length}>지급 내용 확인</button>
    </form></details>
    <details className="rounded-xl border p-4"><summary className="cursor-pointer font-medium">기존 회원의 크레딧 기준 전환</summary><p className="mt-3 text-sm text-muted-foreground">전환은 자동 실행되지 않습니다. 기존 잔액을 아래 비율로 환산해 3개월 유효한 추가 크레딧으로 옮깁니다. 팀은 전원을 함께 선택해야 하며 진행 중 작업이 있으면 차단됩니다.</p><form className="mt-3 flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); submit({ kind: "activate", users: selected, ratio: number(f,"ratio"), reviewed: true, reason: text(f,"reason"), action: crypto.randomUUID() }); }}><label className="grid gap-1 text-sm">기존 몇 크레딧을 새 1크레딧으로?<input name="ratio" className={field} type="number" step="0.01" min="0.01" required /></label><label className="grid gap-1 text-sm">전환 근거<input className={field} name="reason" minLength={3} required /></label><label className="text-sm"><input type="checkbox" required />기존 실패·만료 작업과 회원 잔액을 확인했습니다.</label><button className={button} disabled={!enabled || pending || !selected.length}>전환 내용 확인</button></form></details>
    <details className="rounded-xl border p-4"><summary className="cursor-pointer font-medium">선택 회원 승인·정지</summary><p className="mt-3 text-sm text-muted-foreground">이메일 인증을 마친 대기·정지 회원만 승인되고, 활성 회원만 정지됩니다. 조건에 맞지 않는 회원은 건너뛰고 몇 명이 바뀌었는지 알려 드립니다. <strong>승인 메일은 보내지 않습니다.</strong> 여러 명에게 한 번에 보내면 요청이 먼저 끊깁니다. 메일은 운영 현황 화면에서 회원별로 다시 보낼 수 있습니다.</p><form className="mt-3 flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); submit({ kind: "status", users: selected, status: text(f,"status") as "active" | "suspended", reason: text(f,"reason"), action: crypto.randomUUID() }); }}><label className="grid gap-1 text-sm">바꿀 상태<select name="status" className={field}><option value="active">승인</option><option value="suspended">정지</option></select></label><label className="grid gap-1 text-sm">사유<input className={field} name="reason" minLength={3} required /></label><button className={button} disabled={!enabled || pending || !selected.length}>변경 내용 확인</button></form></details>

    <details className="rounded-xl border p-4"><summary className="cursor-pointer font-medium">구독 상품 설정</summary><p className="my-3 text-sm text-muted-foreground">상품 등록은 회원에게 자동 지급하지 않습니다. 결제 확인된 월별 이용권만 지급됩니다.</p><ul className="mb-3 text-sm">{plans.map(p => <li key={p.id}>{p.name} ({p.id}) · {p.monthly_units}크레딧 · {p.price_krw.toLocaleString()}원 · {p.active ? "사용" : "중지"}</li>)}</ul><form className="flex flex-wrap gap-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); submit({ kind:"plan", plan:text(f,"plan"), name:text(f,"name"), units:number(f,"units"), amount:number(f,"amount"), active:f.get("active") === "on" }); }}><input className={field} aria-label="상품 ID" name="plan" placeholder="상품 ID (영문)" pattern="[a-z0-9_-]+" required /><input className={field} aria-label="상품명" name="name" placeholder="상품명" required /><input className={field} aria-label="월 크레딧" name="units" type="number" min="1" placeholder="월 크레딧" required /><input className={field} aria-label="월 가격" name="amount" type="number" min="0" placeholder="월 가격(원)" required /><label className="text-sm"><input type="checkbox" name="active" />사용</label><button className={button} disabled={!enabled || pending}>저장 내용 확인</button></form></details>
    {focus && <section className="space-y-4 rounded-xl border p-5" aria-label="회원 상세"><div className="flex justify-between gap-3"><h2 className="font-semibold">{focus.email}</h2><button onClick={() => { setFocus(null); setHistory(null); }} className={button}>닫기</button></div>
      <form className="flex flex-wrap gap-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); submit({ kind:"subscription", users:[focus.id], action:crypto.randomUUID(), plan:text(f,"plan"), status:text(f,"status") as "active" | "canceled" | "suspended" }); }}><select className={field} aria-label="구독 상품" name="plan" defaultValue={focus.plan_id ?? ""} required><option value="">상품 선택</option>{plans.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select className={field} aria-label="구독 상태" name="status" defaultValue={focus.subscription_status ?? "active"}><option value="active">이용</option><option value="canceled">해지</option><option value="suspended">중단</option></select><button className={button} disabled={pending}>구독 변경 확인</button></form>
      <form className="flex flex-wrap gap-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); submit({ kind:"paid", user:focus.id, period:`${text(f,"period")}-01`, units:number(f,"units"), amount:number(f,"amount"), action:crypto.randomUUID() }); }}><label className="text-sm">결제 확인 월<input className={field} name="period" type="month" required /></label><input className={field} aria-label="확정 지급 크레딧" name="units" type="number" min="1" placeholder="확정 크레딧" required /><input className={field} aria-label="실제 수령액" name="amount" type="number" min="0" placeholder="수령액(원)" required /><button className={button} disabled={pending}>입금·결제 확인</button></form>
      {!history && <p className="text-sm">이력을 불러오는 중입니다.</p>}
      {history?.pending.map(job => <form key={job.request_id} className="space-y-2 rounded border p-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); submit({ kind:"resolve", user:focus.id, request:job.request_id, positions:f.getAll("position").map(Number), reason:text(f,"reason"), action:crypto.randomUUID() }); }}><p className="text-sm">확인 필요 · {job.operation} · {job.requested_units}크레딧 · {job.credit_phase}</p><p className="text-xs text-muted-foreground">제공된 결과를 확인하고 실제 전달한 이미지만 선택하세요. 하나도 선택하지 않으면 모두 반환합니다.</p><div className="flex flex-wrap gap-3">{job.credit_quote.outputs.map((units,i) => <label key={i} className="text-sm"><input type="checkbox" name="position" value={i} />{i + 1}번 ({units}크레딧)</label>)}</div><input className={field} name="reason" aria-label="정산 근거" placeholder="제공사 결과·저장 이력 확인 근거" minLength={3} required /><button className={button} disabled={pending}>정산 내용 확인</button></form>)}
      <h3 className="text-sm font-semibold">최근 지급 이력</h3>{history?.grants.map(g => <div key={g.id} className="rounded border p-3 text-sm"><p>{g.kind} · 지급 {g.granted_units} · 사용 {g.consumed_units} · 처리 중 {g.reserved_units} · 만료 {date(g.expires_at)}{g.revoked_at ? " · 회수됨" : ""}</p><p className="text-xs text-muted-foreground">{g.reason}</p>{!g.revoked_at && <form className="mt-2 flex flex-wrap gap-2" onSubmit={e => { e.preventDefault(); submit({ kind:"revoke", user:focus.id, grant:g.id, reason:text(new FormData(e.currentTarget),"reason") }); }}><input className={field} name="reason" aria-label="회수 사유" placeholder="미사용분 회수 사유" minLength={3} required /><button className={button} disabled={pending || g.reserved_units > 0}>미사용분 회수 확인</button></form>}</div>)}
      <details><summary className="text-sm">관리자 변경 이력</summary>{history?.audit.map(event => <p key={event.id} className="mt-1 text-xs">{date(event.created_at)} · {event.action} · {event.reason}</p>)}</details>
    </section>}
    {review && <section role="dialog" aria-modal="false" aria-label="변경 내용 확인" className="space-y-3 rounded-xl border-2 border-primary p-5"><h2 className="font-semibold">반영할 내용을 확인하세요</h2><p className="text-sm">{review.kind === "grant" ? `${review.users.length}명에게 각각 ${review.units}크레딧, 수령액 각각 ${review.amount.toLocaleString()}원` : review.kind === "activate" ? `${review.users.length}명 전환 · 기존 ${review.ratio}크레딧 → 새 1크레딧` : review.kind === "paid" ? `${review.period} 이용권 · ${review.units}크레딧 · 수령액 ${review.amount.toLocaleString()}원` : review.kind === "resolve" ? `${review.positions.length}개 결과물 전달 확인 후 나머지 예약 반환` : review.kind === "plan" ? `${review.name} · 매월 ${review.units}크레딧 · ${review.amount.toLocaleString()}원` : review.kind === "subscription" ? `${review.users.length}명 · ${review.plan} · ${review.status}` : review.kind === "status" ? `${review.users.length}명을 ${review.status === "active" ? "승인" : "정지"}합니다. 조건에 맞지 않는 회원은 건너뜁니다` : "선택한 지급 건의 미사용분 회수"}</p>{"reason" in review && <p className="text-sm">사유: {review.reason}</p>}<div className="flex gap-2"><button className={button} disabled={pending} onClick={() => execute(review)}>확인한 내용 반영</button><button className={button} disabled={pending} onClick={() => setReview(null)}>취소</button></div></section>}
    {notice && <p role="status" className="rounded border p-3 text-sm">{notice}</p>}{retry && <button className={button} disabled={pending} onClick={() => execute(retry)}>같은 요청으로 재시도 (중복 지급 방지)</button>}
  </div>;
}
